### ISSUE TITLE
Finish Unit Conversions

### ISSUE THREAD

**Issue by jaydenmilne** [BYU-PCCL/holodeck#249]
**Describe the bug**
The tasks use Unreal units, not meters. We should rectify this.

### Tasks

- [x] `DistanceTask`
- [x] Update config files for `DistanceTask`
- [x] `FollowTask`
- [x] Update config files for `FollowTask`
- [x] `LocationTask`
- [x] Update config files for `LocationTask`
- [x] Identify commands that need to have unit conversion applied
- [x] `SpawnAgentCommand`
- [x] `DebugDrawCommand`
- [x] `TeleportCameraCommand`
- [x] `AddSensorCommand`
- [x] `teleport_buffer`
