### ISSUE TITLE
Enhance Weather Controller

### ISSUE THREAD

**Issue by jaydenmilne** [BYU-PCCL/holodeck#263]
**Describe the new feature you'd like**

Currently the weather commands are all on the `HolodeckEnvironment` class. We've been working on paring this class down (#196), and the last few things to get off of it are the weather and time related methods. We want to move those methods to a weather controller class that is a member of `HolodeckEnvironment`, ie `env.weather.set_day_time(22)`

We also want to add a way to configure the weather and time of day from a scenario file, ie 
```json
{
   "name": "{Scenario Name}",
   "world": "{world it is associated with}",

   "agents":[
      "array of agent objects"
   ],

   "weather": {
      "hour": 22,
      "day_cycle_length": 1,
      "type": "rain",
      "fog": 0.999
   },
   "window_width":  1280,
   "window_height": 720
}
```

The json above is an example, feel free to change it in any way that makes sense. 

This weather from the config file will need to be re-applied every reset.

### TODO
- [x] Weather and time related methods are removed from the `HolodeckEnvironment` class to another class in environments.py
- [x] Class is a member of `HolodeckEnvironment`
- [x] Weather can be specified in config files
    - [x] Weather config block and options are optional and have default values
    - [x] Document how weather works and defaults
- [x] Weather is applied every reset
- [x] `world_command_examples` is updated to use `weather` member on `env`
- [x] Tests!
  - [x] Tests for setting weather/time manually (ie `env.weather.set_fog_density(.9)`)
  - [x] Tests for setting weather/time in scenario config
  - [x] Tests to make sure weather in config persists after reset
  - [x] Validate that weather works in every world (this may be broken - consult @MaxRobinsonTheGreat)

**Comment by jaydenmilne** [comment]
We could update the engine and get better skyboxes as well -> https://docs.unrealengine.com/en-US/Support/Builds/ReleaseNotes/4_24/index.html

**Comment by jaydenmilne** [comment]
Be sure to update #196 when finished 👆

**Comment by jaydenmilne** [comment]
Calling the new class `WeatherController` works but isn't 100% accurate, since it would encompass time methods as well. If we can think of a concise, more descriptive name that'd be great.

**Comment by vinhowe** [comment]
Closed by #372, #375, #387.

**Comment by jaydenmilne** [comment]
✅ in changelog
