### ISSUE TITLE
Rotations are inconsistent with documentation

### ISSUE THREAD

**Issue by jaydenmilne** [BYU-PCCL/holodeck#309]
**Describe the bug**
Our documentation says that rotations are in `[pitch, roll, yaw] / [Y, X, Z]` format. 

Testing indicates that spawning agents is actually in `[yaw, pitch, roll] / [Z, Y, X]` format

[This UE4 answer](https://answers.unrealengine.com/questions/62077/what-is-the-rotation-order-for-components-or-bones.html) seems to indicate means that we are applying a local rotation in that instance.

We need to make sure that we use the same rotation scheme. It probably makes sense for most of the rotations in Holodeck to be world rotation (`[X,Y,Z]`, relative to origin) instead of a local rotation (`[Z, Y, X]`, relative to current rotation).

**Expected behavior**
All rotations in Holodeck are consistent, and the documentation reflects that. Each rotation should

**TODO** 
- [x] Determine & fix rotation order of spawning
- [x] Determine & fix rotation order of teleport
- [x] Determine & fix rotation order of `set_state`
- [x] Determine & fix rotation order of `RotationSensor`
- [x] Determine & fix rotation order of rotating sensors
- [x] Document which rotations are world and which are local
- [x] Make documentation describing difference between world and local rotations

**Comment by jaydenmilne** [comment]
Results

| Item                               | Order          |
|--------------------------|-------------|
| Teleport Command         | `[x, y, z]`      |
| Set State                         | `[x, y, z]`      |
| Rotation Sensor              | `[x, y, z]`      |
| Spawning Agent             | `[y, z, x]`      |
| Sensor Rotation (config) | `[y, z, x]`       |
| Sensor Rotation (dynam)| `[y, z, x]`      |

**Comment by jaydenmilne** [comment]
We are standardizing on the `[x, y, z]` format

**Comment by jaydenmilne** [comment]
✔ in changelog
